### ISSUE TITLE
Can't access the data

### ISSUE THREAD

**Issue by YuxuanZheng94** [stratust/igpipeline#3]
Dear author,

I tried to download the example data through the provided website (http://gofile.me/4kSgZ/cr4CylTqJ), but it failed. Would you help me with that?

Thank you!

**Comment by stratust** [comment]
Hi, I updated the link (https://www.dropbox.com/s/fv21zlqx3dizw1m/data_robbiani_df_2020.zip?dl=0). Please let me know if you still cannot access the data.

**Comment by YuxuanZheng94** [comment]
> Hi, I updated the link (https://www.dropbox.com/s/fv21zlqx3dizw1m/data_robbiani_df_2020.zip?dl=0). Please let me know if you still cannot access the data.

Thank you! The new link is OK!
